# Generated by Django 5.2 on 2025-04-07 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('id__isnull', False)), name='inventory_id_not_null'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.CheckConstraint(condition=models.Q(('id__isnull', False)), name='unit_id_not_null'),
        ),
    ]
